# Generated by Django 5.0.2 on 2024-02-17 09:19

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Please enter a valid first name.', regex='^[a-zA-Z]+(?: [a-zA-Z]+)*$')])),
                ('status', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/cat_image/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('cat_descr', tinymce.models.HTMLField(blank=True, default='')),
                ('slug', models.SlugField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Please enter a valid name.', regex='^[a-zA-Z]+(?: [a-zA-Z]+)*$')])),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Please enter a valid Phone number.', regex='^\\+?1?\\d{9,15}$')])),
                ('locality', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Please enter a valid city name.', regex='^[a-zA-Z]+(?: [a-zA-Z]+)*$')])),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('default', 'Select State'), ('andaman_and_nicobar_islands', 'Andaman and Nicobar Islands'), ('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chandigarh', 'Chandigarh'), ('chhattisgarh', 'Chhattisgarh'), ('dadra_and_nagar_haveli', 'Dadra and Nagar Haveli'), ('daman_and_diu', 'Daman and Diu'), ('delhi', 'Delhi'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jammu_and_kashmir', 'Jammu and Kashmir'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('ladakh', 'Ladakh'), ('lakshadweep', 'Lakshadweep'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('puducherry', 'Puducherry'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal')], default='Select State', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('selling_price', models.FloatField(max_length=4)),
                ('discounted_price', models.FloatField(max_length=4)),
                ('short_description', models.TextField()),
                ('description', tinymce.models.HTMLField(blank=True, default='')),
                ('brand', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='product')),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.category_master')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('packed', 'Packed'), ('on_the_way', 'On the way'), ('delivered', 'Delivered'), ('cancel', 'Cancel')], default='Pending', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product')),
            ],
        ),
    ]
